parser: "@typescript-eslint/parser"

extends:
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"

parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect

rules: {}
