parser: "@typescript-eslint/parser"

extends:
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"

parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect

root: true

rules:
  # I don't usually abuse non-null assertions
  "@typescript-eslint/no-non-null-assertion": 0
