env:
  es6: true
  node: true
  jest: true
  browser: true

parser: "@typescript-eslint/parser"

plugins:
  - react-hooks

extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"

parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect

root: true

rules:
  # I don't usually abuse non-null assertions
  "@typescript-eslint/no-non-null-assertion": 0

  # Noops are often useful as default callbacks
  "@typescript-eslint/no-empty-function": 0

  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 2
  no-trailing-spaces: 2
