os: linux
language: node_js
node_js:
  - 10

cache: npm

before_install:
  - gem update --system
  - gem install jekyll
  - gem install bundler

before_script:
  - chmod +x ./scripts/deploy.sh
  - npm run compile
  - npm test

script:
  - ./scripts/deploy.sh
