os: linux
language: node_js
node_js:
  - 10

cache: npm

before_install:
  - gem update --system
  - gem install jekyll
  - gem install bundler

script:
  - npm run compile
  - npm test

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: develop
  skip_cleanup: true
  committer_from_gh: true
  keep_history: true
  allow_empty_commit: true
  verbose: true
