os: linux
language: node_js
node_js:
  - 10

cache: npm

before_install:
  - npm run compile
  - npm test

install:
  - gem update --system
  - gem install jekyll
  - gem install bundler

script:
  - ./scripts/deploy.sh
