name: Deploy https://parzh.github.io

on:
  push:
    branches: [develop]

# ASSUMPTION:
# The commits are already tested by the '/test-changes.yml' workflow before being pushed to 'develop' branch.
# This should ideally be enforced here:
#   https://github.com/parzh/parzh.github.io/settings/branch_protection_rules/13738671

jobs:
  deploy:
    name: Deploy pages
    runs-on: ubuntu-18.04
    env:
      PAGES_DIST_DIR: _site
      BOT_GIT_NAME: Parzh (bot)
      BOT_GIT_EMAIL: ${{ secrets.BOT_GIT_EMAIL }}
      GIT_REMOTE_NAME: origin

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby >= 2.4
        uses: actions/setup-ruby@v1.0.0
        with:
          version: ">= 2.4"

      - name: Install Jekyll
        run: gem install jekyll

      - name: Configure Git for GitHub Actions
        run: |
          git config user.name "$BOT_GIT_NAME"
          git config user.email "$BOT_GIT_EMAIL"

      - name: Prepare 'master' branch in dist dir
        run: |
          git fetch "$GIT_REMOTE_NAME"
          git worktree add "$PAGES_DIST_DIR" master

      - name: Build local 'master'
        run: jekyll build

      - name: Track everything in dist dir
        working-directory: ./${{ env.PAGES_DIST_DIR }}
        run: git add --all

      - name: Commit changed to local 'master'
        working-directory: ./${{ env.PAGES_DIST_DIR }}
        run: git commit --allow-empty -m "Build from $GITHUB_SHA"

      - name: Sync local and remote 'master'
        working-directory: ./${{ env.PAGES_DIST_DIR }}
        run: git push "$GIT_REMOTE_NAME" master
