name: Deploy https://parzh.github.io

on:
  push:
    branches: [develop]

jobs:
  install:
    name: Install vendors
    runs-on: ubuntu-18.04
    steps:
      - name: Install Ruby >= 2.4
        if: "false" # TODO: remove
        uses: actions/setup-ruby@v1.0.0
        with:
          version: ">= 2.4"

      - name: Install gems
        if: "false" # TODO: remove
        run: |
          gem install jekyll bundler

      - name: Install gems from Gemfile
        if: "false" # TODO: remove
        run: |
          bundle install

      - name: Debug working directory
        run: |
          echo "PROCESS WORKING DIRECTORY: $(pwd)"
          echo "$(ls)"

      - name: Install Node.js 10.x
        uses: actions/setup-node@v1.1.0
        with:
          version: "10.x"

      - name: Install npm dependencies
        run: |
          ls
          exit 1
          npm ci

  test:
    name: Test the source
    runs-on: ubuntu-18.04
    needs: [install]
    steps:
      - name: Check typings
        run: |
          npm run compile

      - name: Run tests
        run: |
          npm test

  deploy:
    name: Deploy pages
    runs-on: ubuntu-18.04
    needs: [test]
    steps:
      - run: |
          chmod +x ./scripts/deploy.sh
          bash ./scripts/deploy.sh
