name: Deploy https://parzh.github.io

on:
  push:
    branches: [develop]

jobs:
  test:
    name: Test the source
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run compile
      - run: npm test

  deploy:
    name: Deploy pages
    runs-on: ubuntu-18.04
    needs: [test]
    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby >= 2.4
        uses: actions/setup-ruby@v1.0.0
        with:
          version: ">= 2.4"

      - name: Install Jekyll
        run: gem install jekyll

      - name: Configure Git for GitHub Actions
        run: |
          git config user.name "GitHub Actions User"
          git config user.email "$GIT_AUTHOR_NAME"

      - name: Prepare 'master' branch in '_site' dir
        run: |
          git fetch origin
          git worktree add _site master

      - name: Build local 'master'
        run: jekyll build

      - name: Track everything in '_step' dir
        run: |
          cd _site
          git add --all

      - name: Commit changed to local 'master'
        run: |
          cd _site
          git commit --allow-empty -m "Build from $GITHUB_SHA"

      - name: Sync local and remote 'master'
        run: |
          cd _site
          git push origin master --no-verify
