name: Deploy https://parzh.github.io

on:
  push:
    branches: [develop]

jobs:
  test:
    name: Test the source
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run compile
      - run: npm test

  # TODO: deploy: