name: Deploy parzh.github.io from

on:
  push:
    branches: [develop]

jobs:
  install:
    name: Install vendors
    runs-on: [linux]
    steps:
      - name: Install Ruby >= 2.4
        uses: actions/setup-ruby@v1.0.0
        with:
          version: ">= 2.4"

      - name: Install Node.js 10.x
        uses: actions/setup-node@v1.1.0
        with:
          version: "10.x"

      - name: Install gems
        run: |
          gem install jekyll bundler
          bundle install

      - name: Install npm dependencies
        run: |
          npm ci

  test:
    name: Test the source
    runs-on: [linux]
    needs: [install]
    steps:
      - name: Check typings
        run: |
          npm run compile

      - name: Run tests
        run: |
          npm test

  deploy:
    name: Deploy pages
    runs-on: [linux]
    needs: [test]
    steps:
      - run: |
          chmod +x ./scripts/deploy.sh
          bash ./scripts/deploy.sh
