name: Test changes

on:
  push:
    paths-ignore:
      - ".github/workflows/debug-gh-actions.yml"
      - README.md
    branches-ignore:
      - "debug-gh-actions/*"

jobs:
  build:
    name: Build the source
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build

  lint:
    name: Check the style
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run lint

  test:
    name: Test the source
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run test:cov
