name: Test changes

on:
  push:
    paths-ignore:
      - ".github/workflows/debug-gh-actions.yml"
      - README.md
    branches-ignore:
      - "debug-gh-actions/*"

jobs:
  lint:
    name: Check the style
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run lint

  test:
    name: Test the source
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm test -- --collect-coverage
      - uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: ./coverage/lcov-report

  coverage:
    name: Deploy coverage report
    runs-on: ubuntu-18.04
    needs: test
    env:
      BOT_GIT_NAME: Parzh (bot)
      BOT_GIT_EMAIL: ${{ secrets.BOT_GIT_EMAIL }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: parzh/coverage-report
          token: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}

      - run: rm -rf ./*

      - uses: actions/download-artifact@v1
        with:
          name: coverage

      - run: mv coverage/* .
      - run: rmdir coverage

      - run: |
          git config user.name "$BOT_GIT_NAME"
          git config user.email "$BOT_GIT_EMAIL"

      - run: git add --all
      - run: git commit --allow-empty -m "Coverage as of $GITHUB_SHA"
      - run: git push origin master
