name: Test changes

on:
  push:
    paths-ignore:
      - ".github/workflows/debug-gh-actions.yml"
      - README.md
    branches-ignore:
      - "debug-gh-actions/*"

jobs:
  lint:
    name: Check the style
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run lint

  test:
    name: Test the source
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm test -- --collect-coverage
      - uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: ./coverage/lcov-report
